# Generated by Django 4.1.7 on 2023-03-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
