# Generated by Django 4.1.7 on 2023-03-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_problem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
