# Generated by Django 4.1.7 on 2023-03-14 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0004_commentlikesdislikes_comment_problem_comment_symptom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_check',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
