# Generated by Django 4.1.7 on 2023-03-14 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_alter_comment_check_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 14, 3, 50, 10, 28932, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
