# Generated by Django 4.1.7 on 2023-03-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_alter_comment_options_comment_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='body',
        ),
    ]
